[package]
name = "bayen"
version = "0.1.0"
edition = "2021"

[dependencies]
ntex = { version = "2.3.0", features = ["tokio"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
utoipa = "4.2.3"
utoipa-swagger-ui = "7.1.0"
url = "2.5.2"

